/// Default `tgbot.yaml` template generated by the `init` command.
const defaultConfigTemplate = '''# Telegram–Codex Bridge Configuration Example
#
# To use this, copy this file to `tgbot.yaml` and fill in your details.

# --- How to get your Telegram Bot Token ---
# 1. Open Telegram and search for @BotFather.
# 2. Send the command `/newbot`.
# 3. Follow the instructions to choose a name and username for your bot.
# 4. @BotFather will provide an API token. Paste it here.

# --- How to get your Telegram User ID ---
# 1. Open Telegram and search for @userinfobot.
# 2. Send any message to it.
# 3. It will reply with your numeric ID (e.g., 123456789). Paste it here.

bots:
  - name: my-bot
    telegram_bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    allowed_user_ids:
      - 123456789
    # Supported values: codex, opencode, gemini, claude.
    # Omit to default to codex.
    provider: codex
    # Optional provider command and args.
    # ai_cli_cmd: codex
    # ai_cli_args:
    #   - --model
    #   - gpt-5
    # ai_cli_timeout_sec: 1000
    # The absolute path to the project you want the bot to interact with.
    # This can be overridden on a per-bot basis.
    project_path: /absolute/path/to/another/project
''';
