/// Default `tgbot.yaml` template generated by the `init` command.
const defaultConfigTemplate = '''# Telegram–AI CLI Bridge Configuration Example
#
# To use this, copy this file to `tgbot.yaml` and fill in your details.

# --- How to get your Telegram Bot Token ---
# 1. Open Telegram and search for @BotFather.
# 2. Send the command `/newbot`.
# 3. Follow the instructions to choose a name and username for your bot.
# 4. @BotFather will provide an API token. Paste it here.

# --- How to get your Telegram User ID ---
# 1. Open Telegram and search for @userinfobot.
# 2. Send any message to it.
# 3. It will reply with your numeric ID (e.g., 123456789). Paste it here.
#
# --- How to get your Telegram Group ID (optional) ---
# 1. Add your bot to the target group/supergroup.
# 2. Send a message in that group.
# 3. Call getUpdates and read message.chat.id (often negative, e.g. -1001234567890).

bots:
  - name: my-bot
    telegram_bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    allowed_user_ids:
      - 123456789
    # Optional: allow a Telegram group/supergroup by chat id.
    # allowed_chat_ids:
    #   - -1001234567890
    # Supported values: codex, cursor, opencode, gemini, claude.
    # Omit to default to codex.
    provider: codex
    # Optional provider command and args.
    # ai_cli_cmd: codex
    # ai_cli_args:
    #   - --model
    #   - gpt-5
    # ai_cli_timeout_sec: 1000
    # final_response_only: true # send only the final assistant reply by default
    # memory: false            # add memory file instructions on first session question
    # memory_filename: MEMORY.md # customize the filename used by memory instructions
    # Optional runtime logging options.
    # log_level: info            # debug, info, warn, error
    # log_format: text           # text or json
    # strict_config: false       # reject unknown keys when true
    # validate_project_path: false # verify project_path exists/readable
    # Optional default project path. Required unless you configure `topics`.
    project_path: /absolute/path/to/another/project
    # Optional: create forum topics by name and map them to projects.
    # topics:
    #   - name: Backend
    #     project_path: /absolute/path/to/backend-project
    #     final_response_only: true
    #     additional_system_prompt: Focus on backend services only.
    #     telegram_commands:
    #       - command: topic_fix
    #         description: Fix this backend issue: {args}
''';
